[package]
name = "place_note"
version = "0.1.0"

[lib]
kind = "note"
namespace = "miden:place-note/miden-place-note@0.1.0"

[dependencies]
miden-core = "*"
miden-protocol = "*"
market = { path = "../../market" }

[package.metadata.miden.dependencies]
market = { wit = "../../market/target/generated-wit/" }
