[package]
name = "resolve-no"
version = "0.1.0"

[lib]
kind = "tx-script"
namespace = "miden:base/transaction-script@1.0.0"

[dependencies]
miden-core = "*"
miden-protocol = "*"
market = { path = "../../contracts/market" }

[package.metadata.miden.dependencies]
market = { wit = "../../contracts/market/target/generated-wit/" }
